import SwiftUI

struct FAQView: View {
    private let entries: [FAQEntry] = FAQEntry.all

    var body: some View {
        NavigationStack {
            List {
                ForEach(entries) { entry in
                    DisclosureGroup {
                        Text(entry.answer)
                            .font(Theme.Font.body)
                            .foregroundStyle(Theme.Color.textSecondary)
                            .padding(.vertical, Theme.Spacing.sm)
                    } label: {
                        Text(entry.question)
                            .font(Theme.Font.heading)
                            .foregroundStyle(Theme.Color.textPrimary)
                    }
                }
            }
            .listStyle(.insetGrouped)
            .navigationTitle("FAQ")
        }
    }
}

struct FAQEntry: Identifiable, Hashable {
    let id = UUID()
    let question: String
    let answer: String

    static let all: [FAQEntry] = [
        .init(question: "What is Debater?",
              answer: "Debater generates structured AI debates and discussions between two personas on a motion you pick. Each turn is produced by an LLM following the rhetorical style of the persona you chose."),
        .init(question: "Which models power the debate?",
              answer: "Debate turns and the judge verdict are generated by OpenAI's GPT family. Persona research uses Perplexity, and deep persona enrichment uses Anthropic Claude Opus."),
        .init(question: "How does the judge decide?",
              answer: "The judge scores each side across clarity, strength, responsiveness, and weighing, plus ten detailed sub-scores. It then produces a ballot linking each decision back to a specific turn, and a final verdict."),
        .init(question: "Can I create my own persona?",
              answer: "Yes. From the Personas tab tap +, enter a subject (real or fictional), and the app will research and synthesize a persona you can then edit and save."),
        .init(question: "Is my history private?",
              answer: "Debates and custom personas you create are scoped to this device. If you reset the app or reinstall, your history won't follow unless you sign in.")
    ]
}
