import SwiftUI

struct FAQView: View {
    private let entries: [FAQEntry] = FAQEntry.all

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: Theme.Spacing.md) {
                    ForEach(entries) { entry in
                        FAQCard(entry: entry)
                    }
                }
                .padding(Theme.Spacing.lg)
            }
            .background(AmbientBackground())
            .navigationTitle("FAQ")
        }
    }
}

private struct FAQCard: View {
    let entry: FAQEntry
    @State private var expanded = false

    var body: some View {
        VStack(alignment: .leading, spacing: Theme.Spacing.sm) {
            Button {
                withAnimation(.spring(response: 0.4, dampingFraction: 0.8)) {
                    expanded.toggle()
                }
            } label: {
                HStack(alignment: .top, spacing: Theme.Spacing.md) {
                    Text(entry.question)
                        .font(Theme.Font.heading)
                        .foregroundStyle(Theme.Color.textPrimary)
                        .multilineTextAlignment(.leading)
                    Spacer()
                    Image(systemName: "chevron.down")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(Theme.Color.accent)
                        .rotationEffect(.degrees(expanded ? 180 : 0))
                }
            }
            .buttonStyle(.plain)
            if expanded {
                Text(entry.answer)
                    .font(Theme.Font.serifBody)
                    .foregroundStyle(Theme.Color.textSecondary)
                    .fixedSize(horizontal: false, vertical: true)
                    .transition(.opacity.combined(with: .move(edge: .top)))
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .glassCard()
    }
}

struct FAQEntry: Identifiable, Hashable {
    let id = UUID()
    let question: String
    let answer: String

    static let all: [FAQEntry] = [
        .init(question: "What is Debater?",
              answer: "Debater generates structured AI debates and discussions between two personas on a motion you pick. Each turn is produced by an LLM following the rhetorical style of the persona you chose."),
        .init(question: "Which models power the debate?",
              answer: "Debate turns and the judge verdict are generated by OpenAI's GPT family. Persona research uses Perplexity, and deep persona enrichment uses Anthropic Claude Opus."),
        .init(question: "How does the judge decide?",
              answer: "The judge scores each side across clarity, strength, responsiveness, and weighing, plus ten detailed sub-scores. It then produces a ballot linking each decision back to a specific turn, and a final verdict."),
        .init(question: "Can I create my own persona?",
              answer: "Yes. From the Personas tab tap +, enter a subject (real or fictional), and the app will research and synthesize a persona you can then edit and save."),
        .init(question: "Is my history private?",
              answer: "Debates and custom personas you create are scoped to this device. If you reset the app or reinstall, your history won't follow unless you sign in.")
    ]
}
