import { StagePlan } from './stage-plan.types.js';

export const DISCUSSION_STAGE_PLAN: StagePlan = {
  mode: 'discussion',
  stages: [
    {
      id: 'MOD_INTRO',
      label: 'Moderator Introduction',
      speaker: 'MOD',
      maxWords: 130,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'MOD_Q1',
      label: 'Opening Question',
      speaker: 'MOD',
      maxWords: 60,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'A_RESPOND_1',
      label: 'Guest A Response 1',
      speaker: 'A',
      maxWords: 150,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'B_RESPOND_1',
      label: 'Guest B Response 1',
      speaker: 'B',
      maxWords: 150,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'MOD_Q2',
      label: 'Follow-up Question',
      speaker: 'MOD',
      maxWords: 70,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'B_RESPOND_2',
      label: 'Guest B Response 2',
      speaker: 'B',
      maxWords: 150,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'A_RESPOND_2',
      label: 'Guest A Response 2',
      speaker: 'A',
      maxWords: 150,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'MOD_SYNTHESIS',
      label: 'Moderator Synthesis',
      speaker: 'MOD',
      maxWords: 80,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'A_FINAL',
      label: 'Guest A Final Thought',
      speaker: 'A',
      maxWords: 100,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
    {
      id: 'MOD_WRAP',
      label: 'Moderator Wrap-up',
      speaker: 'MOD',
      maxWords: 150,
      bullets: null,
      questionRequired: false,
      questionCount: 0,
    },
  ],
};
