import SwiftUI

/// Shown once on first launch. Matches the banner in the web app
/// (frontend/src/app/layout.tsx). Required reading before the user can
/// proceed to the rest of the app.
struct DisclaimerView: View {
    let onAccept: () -> Void

    var body: some View {
        VStack(spacing: Theme.Spacing.xl) {
            Spacer()

            Image(systemName: "exclamationmark.triangle.fill")
                .font(.system(size: 48))
                .foregroundStyle(Theme.Color.moderator)

            Text("Before you begin")
                .font(Theme.Font.display)
                .foregroundStyle(Theme.Color.textPrimary)
                .multilineTextAlignment(.center)

            VStack(spacing: Theme.Spacing.md) {
                disclaimerLine("Every speech in this app is generated by AI. Nothing you see was actually said by the person depicted.")
                disclaimerLine("Personas are rhetorical sketches — style, tone, and plausible positions only. They are not statements of fact about any real individual.")
                disclaimerLine("This app is not affiliated with, endorsed by, or reviewed by any person depicted.")
                disclaimerLine("Use the debates for entertainment, education, and thought experiments — not as a source of quotes or opinions.")
            }
            .padding(.horizontal, Theme.Spacing.md)

            Spacer()

            Button {
                onAccept()
            } label: {
                Text("I understand")
                    .fontWeight(.semibold)
                    .frame(maxWidth: .infinity)
            }
            .buttonStyle(.borderedProminent)
            .controlSize(.large)
            .padding(.horizontal, Theme.Spacing.lg)
        }
        .padding(.vertical, Theme.Spacing.xl)
        .background(Theme.Color.background.ignoresSafeArea())
        .interactiveDismissDisabled()
    }

    private func disclaimerLine(_ text: String) -> some View {
        HStack(alignment: .top, spacing: Theme.Spacing.sm) {
            Image(systemName: "checkmark.circle.fill")
                .foregroundStyle(Theme.Color.accent)
                .font(.system(size: 16))
                .padding(.top, 2)
            Text(text)
                .font(Theme.Font.serifBody)
                .foregroundStyle(Theme.Color.textPrimary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}

enum DisclaimerStore {
    private static let key = "com.debater.disclaimerAcceptedV1"

    static var hasAccepted: Bool {
        UserDefaults.standard.bool(forKey: key)
    }

    static func markAccepted() {
        UserDefaults.standard.set(true, forKey: key)
    }
}
